# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for com.test.Demo

pod 'Alamofire'
pod 'IQKeyboardManagerSwift'
pod 'SwiftyJSON'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'AlamofireObjectMapper', '~> 5.2'

end
